Set-Content -Path ".github/workflows/build.yml" -Value @'
name: Build Windows Installer

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Dépendances racine (electron, electron-builder…)
      - name: Install root deps
        run: npm ci

      # FRONTEND: install puis build (vite)
      - name: Install frontend deps
        run: npm ci
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

      # BACKEND: deps prod uniquement
      - name: Install backend deps (prod only)
        run: npm ci --omit=dev
        working-directory: backend

      # ▶️ Packaging Windows - AUCUNE publication
      - name: Build Windows (NSIS)
        run: npx electron-builder --win nsis --x64 --publish=never --config.directories.output=dist --log-level=debug

      # (facultatif) build Portable pour diagnostic rapide
      - name: Build Windows (Portable)
        run: npx electron-builder --win portable --x64 --publish=never --config.directories.output=dist --log-level=debug

      # Artefacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/**

  # Publication en Release séparée (uniquement si on pousse un tag)
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
'@
